/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Forest_Leaves/forest_leaves_02_1k.gltf --shadows --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/forest_leaves_02_1k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sphere_gltf.geometry}
        material={materials.forest_leaves_02}
      >
        {/* <meshPhysicalMaterial color='hotpink' /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/forest_leaves_02_1k-transformed.glb')
